### ISSUE TITLE
Data set label problem

### ISSUE THREAD

**Issue by wenyu332** [kk7nc/HDLTex#10]
Thank you very much for your paper and data set. However, the labels in the data set are all numerical results. I don't know if it is convenient to provide the relationship between the original label name and the index. Looking forward to your reply

**Comment by kk7nc** [comment]
Thanks for your question. 
If you look at this web we explain everything belong to this dataset,
https://data.mendeley.com/datasets/9rw3vkcfy4/6 
Best,
Kamran

**Comment by wenyu332** [comment]
Thanks for your reply.
I got it. Thank you very much.Your reply has helped me a lot.
Best,
Liu
