### ISSUE TITLE
Error in model 0 try to re-generate an other model DNN  0

### ISSUE THREAD

**Issue by asifraza151** [kk7nc/HDLTex#5]
""Epoch 00001: val_acc improved from -inf to 0.76482, saving model to weights\weights_DNN_0.hdf5
Error in model 0 try to re-generate another model
DNN 0
<keras.optimizers.Adagrad object at 0x7f3339451dd8>
Train on 7769 samples, validate on 3019 samples
Epoch 1/120
Segmentation fault (core dumped)""
this appear when i start to run any examples.
any solution Mr. Kamran

**Comment by kk7nc** [comment]
I think you are running RMDL not HDLTex
Am I right?

**Comment by asifraza151** [comment]
yes bro....

**Comment by kk7nc** [comment]
So can you explain more your data is text or image input and also hardware do you use?
Are you using GPU or CPU?
And please continue conversation on RMDL page https://github.com/kk7nc/RMDL
It could be useful for others

**Comment by kk7nc** [comment]
I create issue : https://github.com/kk7nc/RMDL/issues/2

**Comment by kk7nc** [comment]
and please explain more about your problem
